{% set name = "eth-typing" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8581f212ee6252aaa285377a77620f6e5f6e16ac3f144c61f098fafd47967b1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - typing-extensions >=4.5.0
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - typing-extensions >=4.5.0

test:
  imports:
    - eth_typing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/eth-typing
  summary: 'eth-typing: Common type annotations for ethereum python packages'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
