{% set name = "eth-typing" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f4eface387eefa68761b23743baab8d413d609b4201c4086c64a006be5dbf53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - typing-extensions >=4.0.1
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.0.1

test:
  imports:
    - eth_typing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-typing
  summary: 'eth-typing: Common type annotations for ethereum python packages'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
