{% set name = "eth-typing" %}
{% set version = "4.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 93848083ac6bb4c20cc209ea9153a08b0a528be23337c889f89e1e5ffbe9807d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - typing-extensions >=4.5.0
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.5.0

test:
  imports:
    - eth_typing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-typing
  summary: 'eth-typing: Common type annotations for ethereum python packages'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
